INSERT INTO vegaitdb.country (CountryName) VALUES('Afghanistan');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Albania');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Algeria');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Andorra');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Angola');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Anguilla');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Antigua & Barbuda');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Argentina');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Armenia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Australia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Austria');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Azerbaijan');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Bahamas');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Bahrain');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Bangladesh');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Barbados');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Belarus');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Belgium');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Belize');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Benin');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Bermuda');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Bhutan');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Bolivia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Bosnia & Herzegovina');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Botswana');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Brazil');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Brunei Darussalam');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Bulgaria');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Burkina Faso');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Myanmar/Burma');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Burundi');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Cambodia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Cameroon');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Canada');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Cape Verde');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Cayman Islands');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Central African Republic');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Chad');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Chile');  
INSERT INTO vegaitdb.country (CountryName) VALUES('China');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Colombia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Comoros');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Congo');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Costa Rica');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Croatia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Cuba');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Cyprus');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Czech Republic');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Democratic Republic of the Congo');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Denmark');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Djibouti');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Dominican Republic');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Dominica');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Ecuador');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Egypt');  
INSERT INTO vegaitdb.country (CountryName) VALUES('El Salvador');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Equatorial Guinea');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Eritrea');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Estonia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Ethiopia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Fiji');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Finland');  
INSERT INTO vegaitdb.country (CountryName) VALUES('France');  
INSERT INTO vegaitdb.country (CountryName) VALUES('French Guiana');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Gabon');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Gambia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Georgia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Germany');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Ghana');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Great Britain');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Greece');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Grenada');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Guadeloupe');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Guatemala');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Guinea');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Guinea-Bissau');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Guyana');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Haiti');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Honduras');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Hungary');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Iceland');  
INSERT INTO vegaitdb.country (CountryName) VALUES('India');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Indonesia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Iran');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Iraq');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Israel and the Occupied Territories');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Italy');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Ivory Coast (Cote d''Ivoire)');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Jamaica');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Japan');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Jordan');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Kazakhstan');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Kenya');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Kuwait');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Kyrgyz Republic (Kyrgyzstan)');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Laos');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Latvia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Lebanon');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Lesotho');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Liberia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Libya');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Liechtenstein');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Lithuania');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Luxembourg');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Republic of Macedonia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Madagascar');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Malawi');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Malaysia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Maldives');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Mali');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Malta');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Martinique');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Mauritania');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Mauritius');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Mayotte');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Mexico');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Moldova, Republic of');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Monaco');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Mongolia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Montenegro');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Montserrat');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Morocco');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Mozambique');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Namibia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Nepal');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Netherlands');  
INSERT INTO vegaitdb.country (CountryName) VALUES('New Zealand');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Nicaragua');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Niger');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Nigeria');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Korea, Democratic Republic of (North Korea)');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Norway');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Oman');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Pacific Islands');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Pakistan');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Panama');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Papua New Guinea');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Paraguay');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Peru');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Philippines');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Poland');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Portugal');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Puerto Rico');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Qatar');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Reunion');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Romania');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Russian Federation');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Rwanda');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Saint Kitts and Nevis');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Saint Lucia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Saint Vincent''s & Grenadines');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Samoa');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Sao Tome and Principe');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Saudi Arabia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Senegal');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Serbia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Seychelles');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Sierra Leone');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Singapore');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Slovak Republic (Slovakia)');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Slovenia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Solomon Islands');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Somalia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('South Africa');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Korea, Republic of (South Korea)');  
INSERT INTO vegaitdb.country (CountryName) VALUES('South Sudan');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Spain');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Sri Lanka');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Sudan');  
INSERT INTO vegaitdb.country (CountryName) VALUES('SuriCountryName');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Swaziland');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Sweden');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Switzerland');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Syria');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Tajikistan');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Tanzania');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Thailand');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Timor Leste');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Togo');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Trinidad & Tobago');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Tunisia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Turkey');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Turkmenistan');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Turks & Caicos Islands');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Uganda');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Ukraine');  
INSERT INTO vegaitdb.country (CountryName) VALUES('United Arab Emirates');  
INSERT INTO vegaitdb.country (CountryName) VALUES('United States of America (USA)');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Uruguay');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Uzbekistan');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Venezuela');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Vietnam');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Virgin Islands (UK)');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Virgin Islands (US)');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Yemen');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Zambia');  
INSERT INTO vegaitdb.country (CountryName) VALUES('Zimbabwe'); 